import Drawer from './components/Drawer'
import MobileNav from './components/MobileNav'
import { Providers } from './components/Providers'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className='hidden lg:block'>
            <Drawer />
          </div>
          <MobileNav />
          {children}
        </Providers>
      </body>
    </html>
  )
}
